version: 2

sources:
  - name: globalmart
    description: a clone of the snowflake database
    database: raw
    schema: globalmart
    tables:
      - name: customer
      - name: orders
        description: raw orders table
      - name: product